Improve the oq-engine wrapper and add deprecation warning

diff --git a/bin/oq-engine b/bin/oq-engine
--- a/bin/oq-engine
+++ b/bin/oq-engine
@@ -16,4 +16,15 @@
 #
 # You should have received a copy of the GNU Affero General Public License
 # along with OpenQuake.  If not, see <http://www.gnu.org/licenses/>.
+
+BOLD=`tput bold`
+NORMAL=`tput sgr0`
+
+command -v oq &> /dev/null || {
+    echo -e "!! Can't find 'oq' in your path. Aborting." >&2
+    exit 1
+}
+
+echo "${BOLD}The command 'oq-engine' is deprecated and will be removed. Please use 'oq engine' instead${NORMAL}"
+
 oq engine $@
