deb: make the postinst working on usupported distros

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -30,8 +30,21 @@ if [ "$LSB_RELEASE" = "precise" ]; then
 elif [ "$LSB_RELEASE" = "trusty" ]; then
     PG_VERSION="9.3"
 else
-    echo "This operating system release is not supported"
-    exit 1
+    PG_VERSION=$(sudo -u postgres psql -c'show server_version' -At)
+    PG_VERSION=$(echo "$PG_VERSION" | sed 's/^\([0-9]\+\.[0-9]\+\).*/\1/')
+    if [ -z "$PG_VERSION" ]; then
+        echo "ERROR!! This operating system is running an unsupported version of Postgres."
+        exit 1
+    fi
+
+    echo "=========================================================="
+    echo "WARNING!! You are running an unsupported version of Linux."
+    echo "WARNING!! Use this package at your own risk!"
+    echo "WARNING!! Press ENTER to continue:"
+    echo "=========================================================="
+    if tty -s; then
+        read -n 1 -s
+    fi
 fi
 
 PG_CONF="/etc/postgresql/$PG_VERSION/main/postgresql.conf"
