add start of webUI also on MacOS and curl to test IT

diff --git a/.github/workflows/macos_intel_install.yml b/.github/workflows/macos_intel_install.yml
--- a/.github/workflows/macos_intel_install.yml
+++ b/.github/workflows/macos_intel_install.yml
@@ -53,6 +53,29 @@ jobs:
           oq dbserver start
           sleep 10
 
+      - name: Run test to start OQ-WebUI in public mode to test installation
+        if: always()
+        run: |
+          source ~/openquake/bin/activate
+          oq engine --upgrade-db
+          # Starting the webui here is not needed by test_public_mode,
+          # but here we also want to check that the webui starts without errors
+          oq webui start 127.0.0.1:8800 -s &
+          echo "Waiting WEBUI up on port 8800...."
+          while ! nc -z localhost 8800; do
+           sleep 5 # wait for 5 seconds before check again
+          done
+          echo "Test webui and tools Web pages"
+          sleep 5
+          echo "curl -I --fail -G http://127.0.0.1:8800/engine"
+          curl -I --fail -G http://127.0.0.1:8800/engine
+          sleep 5
+          echo "curl.exe -X HEAD -I --fail http://127.0.0.1:8800/ipt/"
+          curl -X HEAD -I --fail http://127.0.0.1:8800/ipt/
+          sleep 5
+          echo "curl.exe -X HEAD -I --fail http://127.0.0.1:8800/taxonomy/"
+          curl -X HEAD -I --fail http://127.0.0.1:8800/taxonomy/
+
       - name: Run demos to test installation
         run: |
           set -x
@@ -87,19 +110,6 @@ jobs:
           source ~/openquake/bin/activate
           cd ~/work/oq-engine/oq-engine/openquake
           pytest --doctest-modules --disable-warnings --color=yes --durations=10 hazardlib sep commands engine hmtk risklib commonlib baselib
-
-      - name: Run test to start OQ-WebUI in public mode to test installation
-        if: always()
-        run: |
-          source ~/openquake/bin/activate
-          oq engine --upgrade-db
-          # Starting the webui here is not needed by test_public_mode,
-          # but here we also want to check that the webui starts without errors
-          oq webui start 127.0.0.1:8800 -s &
-          echo "Waiting WEBUI up on port 8800...."
-          while ! nc -z localhost 8800; do
-           sleep 5 # wait for 5 seconds before check again
-          done
 
       - name: Run tests for the engine server in public mode to test installation
         if: always()
diff --git a/.github/workflows/macos_m1_install.yml b/.github/workflows/macos_m1_install.yml
--- a/.github/workflows/macos_m1_install.yml
+++ b/.github/workflows/macos_m1_install.yml
@@ -89,6 +89,48 @@ jobs:
           oq engine --upgrade-db
           sleep 5
 
+      - name: Run test to start OQ-WebUI in public mode to test installation
+        if: always()
+        run: |
+          source ~/openquake/bin/activate
+          oq engine --upgrade-db
+          # Starting the webui here is not needed by test_public_mode,
+          # but here we also want to check that the webui starts without errors
+          oq webui start 127.0.0.1:8800 -s &
+          echo "Waiting WEBUI up on port 8800...."
+          while ! nc -z localhost 8800; do
+           sleep 5 # wait for 5 seconds before check again
+          done
+          echo "Test webui and tools Web pages"
+          sleep 5
+          echo "curl -I --fail -G http://127.0.0.1:8800/engine"
+          curl -I --fail -G http://127.0.0.1:8800/engine
+          sleep 5
+          echo "curl.exe -X HEAD -I --fail http://127.0.0.1:8800/ipt/"
+          curl -X HEAD -I --fail http://127.0.0.1:8800/ipt/
+          sleep 5
+          echo "curl.exe -X HEAD -I --fail http://127.0.0.1:8800/taxonomy/"
+          curl -X HEAD -I --fail http://127.0.0.1:8800/taxonomy/
+
+      - name: Run demos to test installation
+        run: |
+          set -x
+          source ~/openquake/bin/activate
+          oq info venv
+          oq info cfg
+          cd ~/work/oq-engine/oq-engine/demos
+          ls -lrt
+          # run demos with job_hazard.ini and job_risk.ini
+          for demo_dir in $(find . -type d | sort); do
+             if [ -f $demo_dir/job_hazard.ini ]; then
+                 oq engine --run $demo_dir/job_hazard.ini --exports csv,hdf5
+                 oq engine --run $demo_dir/job_risk.ini --exports csv,hdf5 --hc -1
+             fi
+          done
+          # run the other demos
+          for ini in $(find . -name job.ini | sort); do
+              oq engine --run $ini --exports csv,hdf5
+          done
       - name: Run tests for calculators to test installation
         if: always()
         run: |
@@ -104,18 +146,6 @@ jobs:
           cd /Users/runner/runner-isolation/actions-runner/_work/oq-engine/oq-engine/openquake/
           pytest --doctest-modules --disable-warnings --color=yes --durations=10 hazardlib sep commands engine hmtk risklib commonlib baselib
 
-      - name: Run test to start OQ-WebUI in public mode to test installation
-        if: always()
-        run: |
-          source ~/openquake/bin/activate
-          oq engine --upgrade-db
-          # Starting the webui here is not needed by test_public_mode,
-          # but here we also want to check that the webui starts without errors
-          oq webui start 127.0.0.1:8800 -s &
-          echo "Waiting WEBUI up on port 8800...."
-          while ! nc -z localhost 8800; do
-           sleep 5 # wait for 5 seconds before check again
-          done
 
       - name: Run tests for the engine server in public mode to test installation
         if: always()
@@ -132,25 +162,3 @@ jobs:
           cd /Users/runner/runner-isolation/actions-runner/_work/oq-engine/oq-engine/
           pip3 install https://wheelhouse.openquake.org/v3/py/pytest_django-4.9.0-py3-none-any.whl
           OQ_APPLICATION_MODE=READ_ONLY pytest -v openquake/server/tests/test_read_only_mode.py
-
-      # NB: the demos are tested on linux; there is no reason a demo should
-      # not run on macos, so we can avoid running them
-      # - name: Run demos to test installation
-      #   run: |
-      #     set -x
-      #     source ~/openquake/bin/activate
-      #     oq info venv
-      #     oq info cfg
-      #     cd /Users/runner/runner-isolation/actions-runner/_work/oq-engine/oq-engine/demos
-      #     ls -lrt
-      #     # run demos with job_hazard.ini and job_risk.ini
-      #     for demo_dir in $(find . -type d | sort); do
-      #        if [ -f $demo_dir/job_hazard.ini ]; then
-      #            oq engine --run $demo_dir/job_hazard.ini --exports csv,hdf5
-      #            oq engine --run $demo_dir/job_risk.ini --exports csv,hdf5 --hc -1
-      #        fi
-      #     done
-      #     # run the other demos
-      #     for ini in $(find . -name job.ini | sort); do
-      #         oq engine --run $ini --exports csv,hdf5
-      #     done
